[workspace]
name = "Parcels"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
requires-pixi = ">=0.63.0"

[dependencies]

[feature.minimum.dependencies]
python = "3.11.*"
netcdf4 = "1.6.*"
numpy = "2.1.*"
tqdm = "4.50.*"
xarray = "2024.5.*"
uxarray = "2025.3.*"
dask = "2024.5.*"
zarr = "2.15.*"
xgcm = "0.9.*"
cf_xarray = "0.8.*"
cftime = "1.6.*"
pooch = "1.8.*"


[feature.test.dependencies]
nbval = "*"
pytest = "*"
hypothesis = "*"
pytest-html = "*"
pytest-cov = "*"


[environments]
default = { features = [
  "test", "minimum"
], solve-group = "main" }
